INSERT INTO PUBLIC.PERSON(EMAIL, DISPLAY_NAME) VALUES('matti@vaadin.com', 'Matti Tahvonen');
INSERT INTO PUBLIC.USER_GROUP(ID, NAME, ADMIN_EMAIL) VALUES(1, 'PMS', 'matti@vaadin.com');
INSERT INTO PUBLIC.PERSON_GROUPS(PERSON_EMAIL, GROUPS_ID) VALUES('matti@vaadin.com', 1);
INSERT INTO PUBLIC.STYLE(ID, COLOR, NAME, VERSION, GROUP_ID) VALUES(1, 'blue', 'Normal', 0, 1);
INSERT INTO PUBLIC.STYLE(ID, COLOR, NAME, VERSION, GROUP_ID) VALUES(2, 'red', 'Important', 0, 1);
